travis:
  secure:
    BINSTAR_TOKEN: pLI2h1rtGk9YrG4kRz5iBwxicICjkhPhJw9a70IWZ6BD7rmvJpjqjZvtz7UmyZ54UoGnQd1SN8LGZP1w6IyKhC60QlzLQkaZrorDeV7fYvTKyangVxuEhz+JyzmZ4gpj91VTBk9H79Rxe5zmugcvOAT17ZQSW3oBd88WoMnGHFhLYywqDcAksPRixPwu5zgUWVdo9daGy0xoVIuxq5oMyr5bOv89wvfBWJqhpqBIUuzjpLNZMScmhiVVfhLczzDn9CmBSPfJNJBSXGu141+ygi80cu9zQl6HkBqjGjbSeydZhiZUs9Fot7Eh8l1QzUYMiPfmk0eTdZnVoSICEOfncwdFET2FvIpSwskcdQjK//cGjFfIneVlk5cF3So1nJaBjQaRGYQC1pqdLmRkuZZS7TpzPvCsnL+9fRA2HXk86QgNkAr3dGWQEGLxvpTu4iUlHatjV5LI5R0HSUeUyoXrkhNAn24vEwoEtgj/RIiTK49mdFHsZJjBMGAbfr4th93JHtdiTc53WUy55Y58GVlU08HnbBOvetD8cnb9OfGw6/0+0azA9qOWDhPV5FC9lWcptopIZmSXZZklXwovsJImfLAR7g3HFEbG/7G8cQeLBpjVzikc/z9G9f2NVb4QoC2w2j05ko0wjqtdecIb/+i4nCgfzloXODJpGZQ4Hs2k1nI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
